#!/usr/bin/env python 
#coding:utf8
#yemaofeng
#2017/06/08
import paramiko
import sys
port = 22
username = "root"
command = " ".join(sys.argv[1:]) ####获取命令行参数 
file=open("ip.list")
for line in file:
        
        hostname=str(line.split()[1]) #截取ip字段 
        password=str(line.split()[4]).strip()
        print "######################",hostname,"####################"
        s=paramiko.SSHClient()#调用paramiko模块下的SSHClient()
        s.set_missing_host_key_policy(paramiko.AutoAddPolicy())##加上这句话不用担心选yes的问题，会自动选上（用ssh连接远程主机时，第一次连接时会提示是否继续>进行远程连接，选择yes）
        s.connect(hostname,port,username,password) #连接远程主机
        stdin,stdout,sterr=s.exec_command(command)  #执行命令
        print stdout.read()
        s.close()
file.close()
