#!/usr/bin/env python
#coding=utf8

import MySQLdb
con = MySQLdb.connect(
    host='localhost',
    user='root',
    passwd='123456',
    db='student'
)
cur = con.cursor()
#创建表格
#cur.execute('create table stu_info (name char(128) not null default "", age tinyint(3) not null default 0, sex enum("man","femal") not null default "man") engine=innodb charset=utf8')
#con.commit()
#插入数据
cur.execute("insert into stu_info (name, age, sex) values ('Yi_Zhi_Yu',25,'man')")
con.commit()
#查询表数据
cur.execute("select * from stu_info")
stus =cur.fetchall()
