#!/usr/bin/env python 
#coding:utf8
#yemaofeng
#2017/06/07
import paramiko
port = 22
username = "root"
file=open("ip.list")
for line in file:
        try:
                hostname=str(line.split()[1]) # ni   jiu   shi   zai   zhe  li  bao  cuo   de 
        except Exception,e:
                hostname_= line.split()       # ni   jiu   shi   zai   zhe  li  bao  cuo   de 
                print hostname_,88888888888888888
                raise IOError('gogogogogogogo')

        #hostname=line[1]
        #password=str(line.split("\t")[4]).strip()
        try:
                password=str(line.split()[4]).strip()
        except Exception,e:
                print  "Error..................",  line.split("\t")[4]
                raise IOError('gogogogogogogo')
        print "######################",hostname,"####################"
        s=paramiko.SSHClient()
        s.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        s.connect(hostname,port,username,password)
        stdin,stdout,sterr=s.exec_command("df -Th")
        print stdout.read()
        s.close()
file.close()


ip.list
dx 192.168.216.128 22 root 1qaz2wsx
wx 192.168.216.130 22 root 1qaz2wsx
sc 192.168.216.129 22 root 1qaz2wsx
